import type { Activity, Child } from "../types";

export const MOCK_CHILDREN: Child[] = [
  {
    id: "child-1",
    name: "Seon",
    grade: "3ème",
    age: 14,
    avatarEmoji: "🚀",
    xp: 1250,
    coins: 45,
    streak: 7,
  },
  {
    id: "child-2",
    name: "Léa",
    grade: "6ème",
    age: 11,
    avatarEmoji: "🦋",
    xp: 890,
    coins: 32,
    streak: 3,
  },
];

const now = new Date();
const hoursAgo = (h: number) => new Date(now.getTime() - h * 60 * 60 * 1000);
const daysAgo = (d: number) =>
  new Date(now.getTime() - d * 24 * 60 * 60 * 1000);

export const MOCK_ACTIVITIES: Activity[] = [
  {
    id: "act-1",
    childId: "child-1",
    type: "quiz",
    subject: "Mathématiques",
    title: "Quiz : Arithmétique — PGCD et fractions",
    score: 85,
    xpEarned: 25,
    duration: 12,
    timestamp: hoursAgo(0.5),
  },
  {
    id: "act-2",
    childId: "child-1",
    type: "dictée",
    subject: "Français",
    title: "Dictée : Accord du participe passé",
    score: 72,
    xpEarned: 20,
    duration: 8,
    timestamp: hoursAgo(1.5),
  },
  {
    id: "act-3",
    childId: "child-1",
    type: "chat",
    subject: "Mathématiques",
    title: "Discussion : Équations du 1er degré",
    xpEarned: 15,
    duration: 18,
    timestamp: hoursAgo(3),
  },
  {
    id: "act-4",
    childId: "child-1",
    type: "exercice",
    subject: "Sciences",
    title: "Exercices : Structure de l'atome",
    score: 90,
    xpEarned: 30,
    duration: 15,
    timestamp: hoursAgo(5),
  },
  {
    id: "act-5",
    childId: "child-1",
    type: "brevet_blanc",
    subject: "Français",
    title: "Brevet blanc : Grammaire & Compréhension",
    score: 78,
    xpEarned: 50,
    duration: 45,
    timestamp: daysAgo(1),
  },
  {
    id: "act-6",
    childId: "child-1",
    type: "calcul_mental",
    subject: "Mathématiques",
    title: "Calcul mental : Fractions — Niveau moyen",
    score: 95,
    xpEarned: 15,
    duration: 5,
    timestamp: daysAgo(1),
  },
  {
    id: "act-7",
    childId: "child-1",
    type: "fiche",
    subject: "Histoire-Géo",
    title: "Fiche : La Seconde Guerre mondiale",
    xpEarned: 10,
    duration: 20,
    timestamp: daysAgo(2),
  },
  {
    id: "act-8",
    childId: "child-1",
    type: "lecture",
    subject: "Français",
    title: "Lecture : Candide — Voltaire",
    xpEarned: 5,
    duration: 30,
    timestamp: daysAgo(2),
  },
  {
    id: "act-9",
    childId: "child-1",
    type: "quiz",
    subject: "Anglais",
    title: "Quiz : Present perfect vs Past simple",
    score: 60,
    xpEarned: 15,
    duration: 10,
    timestamp: daysAgo(3),
  },
  {
    id: "act-10",
    childId: "child-1",
    type: "exercice",
    subject: "Programmation",
    title: "Python : Les boucles for et while",
    score: 100,
    xpEarned: 35,
    duration: 25,
    timestamp: daysAgo(3),
  },
  {
    id: "act-11",
    childId: "child-2",
    type: "quiz",
    subject: "Mathématiques",
    title: "Quiz : Fractions — Addition et soustraction",
    score: 70,
    xpEarned: 20,
    duration: 10,
    timestamp: hoursAgo(2),
  },
  {
    id: "act-12",
    childId: "child-2",
    type: "dictée",
    subject: "Français",
    title: "Dictée : Les homophones grammaticaux",
    score: 88,
    xpEarned: 25,
    duration: 7,
    timestamp: daysAgo(1),
  },
  {
    id: "act-13",
    childId: "child-2",
    type: "chat",
    subject: "Sciences",
    title: "Discussion : Le système solaire",
    xpEarned: 10,
    duration: 12,
    timestamp: daysAgo(1),
  },
];
